/* AUTO-GENERATED by scripts/convert-template.mjs — do not edit */
export type TemplatePageMeta = {
  route: string;
  file: string;
  slug: string;
  title: string;
  bodyClass: string;
};

export const TEMPLATE_PAGES: TemplatePageMeta[] = [
  {
    "route": "/",
    "file": "index.html",
    "slug": "index",
    "title": "REOVANA — Foreclosed Homes",
    "bodyClass": "popup-loader theme-color-4"
  },
  {
    "route": "/agents",
    "file": "agents.html",
    "slug": "agents",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/agents/details",
    "file": "agents-details.html",
    "slug": "agents__details",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/agency/grid",
    "file": "agency-grid.html",
    "slug": "agency__grid",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/agency/list",
    "file": "agency-list.html",
    "slug": "agency__list",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/agency/details",
    "file": "agency-details.html",
    "slug": "agency__details",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/blog/grid",
    "file": "blog-grid.html",
    "slug": "blog__grid",
    "title": "Foreclosure Insights — REOVANA",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/blog/list",
    "file": "blog-list.html",
    "slug": "blog__list",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/blog/details",
    "file": "blog-details.html",
    "slug": "blog__details",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/project/list",
    "file": "project-list.html",
    "slug": "project__list",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/project/details",
    "file": "project-details.html",
    "slug": "project__details",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/property/detail/v1",
    "file": "property-detail-v1.html",
    "slug": "property__detail__v1",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/contact",
    "file": "contact.html",
    "slug": "contact",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/faq",
    "file": "faq.html",
    "slug": "faq",
    "title": "FAQ — REOVANA",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/compare",
    "file": "compare.html",
    "slug": "compare",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/home-loan-process",
    "file": "home-loan-process.html",
    "slug": "home-loan-process",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/dashboard",
    "file": "dashboard.html",
    "slug": "dashboard",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "bg-dashboard theme-color-4"
  },
  {
    "route": "/add-property",
    "file": "add-property.html",
    "slug": "add-property",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "bg-dashboard theme-color-4"
  },
  {
    "route": "/my-property",
    "file": "my-property.html",
    "slug": "my-property",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "bg-dashboard theme-color-4"
  },
  {
    "route": "/my-profile",
    "file": "my-profile.html",
    "slug": "my-profile",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "bg-dashboard theme-color-4"
  },
  {
    "route": "/my-favorites",
    "file": "my-favorites.html",
    "slug": "my-favorites",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "bg-dashboard theme-color-4"
  },
  {
    "route": "/my-package",
    "file": "my-package.html",
    "slug": "my-package",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "bg-dashboard theme-color-4"
  },
  {
    "route": "/my-save-search",
    "file": "my-save-search.html",
    "slug": "my-save-search",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "bg-dashboard theme-color-4"
  },
  {
    "route": "/review",
    "file": "review.html",
    "slug": "review",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "bg-dashboard theme-color-4"
  },
  {
    "route": "/template-404",
    "file": "404.html",
    "slug": "template-404",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  }
];

export const ROUTE_TO_SLUG: Record<string, string> = {
  "/": "index",
  "/agents": "agents",
  "/agents/details": "agents__details",
  "/agency/grid": "agency__grid",
  "/agency/list": "agency__list",
  "/agency/details": "agency__details",
  "/blog/grid": "blog__grid",
  "/blog/list": "blog__list",
  "/blog/details": "blog__details",
  "/project/list": "project__list",
  "/project/details": "project__details",
  "/property/detail/v1": "property__detail__v1",
  "/contact": "contact",
  "/faq": "faq",
  "/compare": "compare",
  "/home-loan-process": "home-loan-process",
  "/dashboard": "dashboard",
  "/add-property": "add-property",
  "/my-property": "my-property",
  "/my-profile": "my-profile",
  "/my-favorites": "my-favorites",
  "/my-package": "my-package",
  "/my-save-search": "my-save-search",
  "/review": "review",
  "/template-404": "template-404"
};

export const SLUG_TO_ROUTE: Record<string, string> = {
  "index": "/",
  "agents": "/agents",
  "agents__details": "/agents/details",
  "agency__grid": "/agency/grid",
  "agency__list": "/agency/list",
  "agency__details": "/agency/details",
  "blog__grid": "/blog/grid",
  "blog__list": "/blog/list",
  "blog__details": "/blog/details",
  "project__list": "/project/list",
  "project__details": "/project/details",
  "property__detail__v1": "/property/detail/v1",
  "contact": "/contact",
  "faq": "/faq",
  "compare": "/compare",
  "home-loan-process": "/home-loan-process",
  "dashboard": "/dashboard",
  "add-property": "/add-property",
  "my-property": "/my-property",
  "my-profile": "/my-profile",
  "my-favorites": "/my-favorites",
  "my-package": "/my-package",
  "my-save-search": "/my-save-search",
  "review": "/review",
  "template-404": "/template-404"
};

export function getTemplateMetaByRoute(route: string): TemplatePageMeta | undefined {
  return TEMPLATE_PAGES.find((p) => p.route === route);
}

export function getTemplateMetaBySlug(slug: string): TemplatePageMeta | undefined {
  return TEMPLATE_PAGES.find((p) => p.slug === slug);
}
